version: '3'
services:
  rails:
    build: .
    image: 'my/rails'
    container_name: 'rails${VERSION}'
    tty: true
    ports:
      - "${RAILS_LOCAL_PORT}:3000"
    environment:
      APP_DATABASE: 'example'
      APP_DATABASE_USER: 'app'
      APP_DATABASE_PASSWORD: 'development'
    volumes:
      - app-data:/usr/src/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: 'mysql${VERSION}'
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'example'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'development'
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  app-data:
     driver: local
  mysql-data:
    driver: local
